---
- name: Update systems
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:

    - name: Update packages (ubuntu)
      tags:
        - update
        - ubuntu
      ansible.builtin.apt:
        update_cache: true
        upgrade: safe
      when: ansible_facts['os_family'] == "Debian"

    - name: Update packages (rocky)
      tags:
        - update
        - rocky
      ansible.builtin.dnf:
        update_cache: true
        update_only: true
      when: ansible_facts['os_family'] == "RedHat"


- name: Base play
  hosts: all
  become: true
  roles:
    - base


- name: Databases play
  hosts: db_servers
  become: true
  roles:
    - db_servers


- name: RDP access play
  hosts: rdp
  become: true
  roles:
    - rdp


- name: Web servers play
  hosts: web_servers
  become: true
  roles:
    - web_servers

- name: Gitlab community instance (from ansible galaxy)
  become: true
  hosts: gitlab_ce
  roles:
    - srv6d.gitlab.ce
  vars:
    gitlab_external_url: "https://git.example.com"
