---
- name: Update systems
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:

    - name: Update packages (ubuntu)
      tags:
        - update
        - ubuntu
      ansible.builtin.apt:
        update_cache: true
        upgrade: safe
      when: ansible_facts['os_family'] == "Debian"

    - name: Update packages (rocky)
      tags:
        - update
        - rocky
      ansible.builtin.dnf:
        update_cache: true
        update_only: true
      when: ansible_facts['os_family'] == "RedHat"


- name: Configure developer system
  import_playbook: users_rdp.yml

- name: Install database
  import_playbook: db_servers.yml


- name: Web servers play
  hosts: web_servers
  become: true
  roles:
    - web_nginx

- name: Gitlab community instance (from ansible galaxy)
  become: true
  hosts: gitlab_ce
  roles:
    - srv6d.gitlab.ce
  vars:
    gitlab_external_url: "{{ gitlab_url }}"

- name: Gitlab runners (from ansible galaxy)
  hosts: gitlab_runners
  roles:
    - srv6d.gitlab.runner
  vars:
    gitlab_runner_ci_server_url: "{{ gitlab_runner_url }}"
    gitlab_runner_registration_token: "{{ gitlab_token }}"

- name: Linux host firewalls
  hosts: web_servers
  roles:
    - linux_firewalls

- name: Apache HTTP server testing environment
  hosts: web_servers
  become: true
  roles:
    - web_apache
