---
- name: Install Apache web server for RedHat based systems (CentOS)
  ansible.builtin.import_tasks: redhat.yml
  when:
    - ansible_facts['os_family'] == "RedHat"

- name: Install Apache web server for Debian based systems (Ubuntu)
  ansible.builtin.import_tasks: debian.yml
  when:
    - ansible_facts['os_family'] == "Debian"


- name: Set groups and user accounts for Apache web server
  ansible.builtin.import_tasks: apache_user_management.yml

- name: Copy website files to Apache web server
  ansible.builtin.copy:
    src: website_apache/
    dest: "{{ apache_root }}"
    owner: root
    group: www-pub
    mode: u=rwx,g=rwx,o=r

- name: Allow user directories
  ansible.builtin.lineinfile:
    path: "{{ apache_config_file }}"
    regexp: '^\s*UserDir'
    line: UserDir public_html

- name: Configuration for user directories
  ansible.builtin.lineinfile:
    path: "{{ apache_userdir_file }}"
    regexp: '^\s*UserDir'
    line: UserDir enabled

- name: Start httpd service (Apache HTTP server)
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true
