- name: Install and configure firewalld on RedHat based systems
  ansible.builtin.import_tasks: set_firewalld.yml
  when:
    - ansible_facts['os_family'] == "RedHat"

- name: Install and configure UFW on Debian based systems
  ansible.builtin.import_tasks: set_ufw.yml
  when:
    - ansible_facts['os_family'] == "Debian"
