- name: Make sure firewalld is installed
  tags: firewalls , rocky
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Permanently enable http service
  ansible.posix.firewalld:
    service: https
    state: enabled
    permanent: true
    immediate: true
    offline: true
